src/objects/Child__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent</label>
        <referenceTo>Parent__c</referenceTo>
        <relationshipLabel>Children</relationshipLabel>
        <relationshipName>Children</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Child</label>
    <nameField>
        <label>Child Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Parent__c.object
<CustomObject>
    <label>Parent</label>
    <nameField>
        <label>Parent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/soql.cls
public class soql {
    public static void findQyery(){
        Map<String, List<Child__c>> parentWithChild = new Map<String, List<Child__c>>();
			for (Parent__c p : [
            SELECT Name, (SELECT  Name FROM Children__r)
            FROM Parent__c
            ])	{ 
                System.debug(p.Children__r);
                parentWithChild.put(p.Name, p.Children__r);
                System.debug(parentWithChild);
            	}
	}
        
}