src/objects/Media__c.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Audio</fullName>
                </value>
                <value>
                    <fullName>Video</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MediaContactPage.cls
/**
 * Created by User on 31.07.2018.
 */

public with sharing class MediaContactPage {
    public List<selectOption> options{get;set;}
    public String myValue{get;set;}
    public List<Media__c> mediaList{get;set;}


    public  MediaContactPage() {
        options = new List<selectOption>();
        options.add( new SelectOption('','--Select--'));
            for(Contact cont : [select Id, name from Contact ] ) {
                options.add(new SelectOption(cont.Id,cont.name));
                System.debug(cont);
            }
        System.debug(options);
    }
//
    public PageReference showMedia(){
        mediaList = [
                SELECT name, type__c, url__c
                FROM Media__c];
        return null;
    }



}