src/objects/Media__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Medias</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Media</label>
    <nameField>
        <label>Media Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MediaTriggerHandler.cls
public class MediaTriggerHandler {

    
    public static void setLookup(List<Media__c> newMedia) {
        Contact defaultCont = new Contact();
        defaultCont.LastName = 'Default';
        insert defaultCont;
        System.debug(newMedia);
        System.debug('Trigger fired');
        System.debug(newMedia[0].Contact__c);
        System.debug(defaultCont);
        if (newMedia[0].Contact__c == null) {
            newMedia[0].Contact__c = defaultCont.Id;
    }
        System.debug(newMedia[0].Contact__c);
        //update newMedia;

    }
}